apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
name: hpa-memory
namespace: demoapp1
spec:
scaleTargetRef:
  apiVersion: apps/v1beta1
  kind: Deployment
  name: nginx
minReplicas: 3
maxReplicas: 6
metrics:
- type: Resource
  resource:
    name: memory
    target:
      type: AverageValue
      averageValue: 100Mi