apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-pod-kill
  namespace: demoapp1
spec:
  appinfo:
    appns: 'demoapp1'
    applabel: 'app=nginx'
    appkind: 'deployment'
  annotationCheck: 'true'
  engineState: 'active'
  auxiliaryAppInfo: ''
  chaosServiceAccount: pod-delete-sa
  jobCleanUpPolicy: 'delete'
  monitoring: false
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            # duurtijd experiment
            - name: TOTAL_CHAOS_DURATION
              value: '30'
            - name: FORCE
              value: 'false'
            # iteratie toevoegen (experiment 2)
            #- name: CHAOS_INTERVAL
            #  value: '10'
