apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress
  namespace: demoapp1
spec:
  mode: all
  duration: '120s'
  selector:
    namespaces:
      - demoapp1
    labelSelectors:
      app: nginx
  stressors:
    memory:
      workers: 4
      size: '100MB'